apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: go-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: go-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-pod
        image: samdjstevens/k8s-test
        ports:
        - containerPort: 8080